/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutEmployeesIndexRouteImport } from './routes/_layout/employees/index'
import { Route as LayoutEmployeesCreateIndexRouteImport } from './routes/_layout/employees/create/index'
import { Route as LayoutEmployeesIdEditIndexRouteImport } from './routes/_layout/employees/$id/edit/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmployeesIndexRoute = LayoutEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmployeesCreateIndexRoute =
  LayoutEmployeesCreateIndexRouteImport.update({
    id: '/employees/create/',
    path: '/employees/create/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEmployeesIdEditIndexRoute =
  LayoutEmployeesIdEditIndexRouteImport.update({
    id: '/employees/$id/edit/',
    path: '/employees/$id/edit/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/employees/': typeof LayoutEmployeesIndexRoute
  '/employees/create/': typeof LayoutEmployeesCreateIndexRoute
  '/employees/$id/edit/': typeof LayoutEmployeesIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/employees': typeof LayoutEmployeesIndexRoute
  '/employees/create': typeof LayoutEmployeesCreateIndexRoute
  '/employees/$id/edit': typeof LayoutEmployeesIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/employees/': typeof LayoutEmployeesIndexRoute
  '/_layout/employees/create/': typeof LayoutEmployeesCreateIndexRoute
  '/_layout/employees/$id/edit/': typeof LayoutEmployeesIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/employees/'
    | '/employees/create/'
    | '/employees/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/employees'
    | '/employees/create'
    | '/employees/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/login/'
    | '/_layout/employees/'
    | '/_layout/employees/create/'
    | '/_layout/employees/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/employees/': {
      id: '/_layout/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof LayoutEmployeesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/employees/create/': {
      id: '/_layout/employees/create/'
      path: '/employees/create'
      fullPath: '/employees/create/'
      preLoaderRoute: typeof LayoutEmployeesCreateIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/employees/$id/edit/': {
      id: '/_layout/employees/$id/edit/'
      path: '/employees/$id/edit'
      fullPath: '/employees/$id/edit/'
      preLoaderRoute: typeof LayoutEmployeesIdEditIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEmployeesIndexRoute: typeof LayoutEmployeesIndexRoute
  LayoutEmployeesCreateIndexRoute: typeof LayoutEmployeesCreateIndexRoute
  LayoutEmployeesIdEditIndexRoute: typeof LayoutEmployeesIdEditIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEmployeesIndexRoute: LayoutEmployeesIndexRoute,
  LayoutEmployeesCreateIndexRoute: LayoutEmployeesCreateIndexRoute,
  LayoutEmployeesIdEditIndexRoute: LayoutEmployeesIdEditIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
